"use client";

import { FormEvent, useEffect, useRef, useState } from "react";

type Entry = { word: string; phonetic: string; wordType: string; meaning: string; cefrLevel: string };
export default function Dictionary({ onUpdated }: { onUpdated: () => void }) {
  const [word, setWord] = useState(""), [entry, setEntry] = useState<Entry | null>(null), [loading, setLoading] = useState(false), [error, setError] = useState(""), [message, setMessage] = useState("");
  const voices = useRef<SpeechSynthesisVoice[]>([]);
  useEffect(() => { const load = () => { voices.current = speechSynthesis.getVoices().filter((voice) => voice.lang.toLowerCase().startsWith("fr")); }; load(); speechSynthesis.addEventListener("voiceschanged", load); return () => speechSynthesis.removeEventListener("voiceschanged", load); }, []);
  async function lookup(event: FormEvent) { event.preventDefault(); if (!word.trim()) return; setLoading(true); setError(""); try { const response = await fetch("/api/analyze", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ word: word.trim() }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setEntry(data); } catch { setError("查询失败，请重试"); } finally { setLoading(false); } }
  function play() { if (!entry) return; setError(""); speechSynthesis.cancel(); speechSynthesis.resume(); const utterance = new SpeechSynthesisUtterance(entry.word); const available = speechSynthesis.getVoices().filter((item) => item.lang.toLowerCase().startsWith("fr")); const voice = available.find((item) => item.lang.toLowerCase() === "fr-fr") || available[0] || voices.current[0]; if (voice) utterance.voice = voice; utterance.lang = "fr-FR"; utterance.rate = .78; utterance.onerror = () => setError("无法播放。请检查浏览器声音权限，或安装法语系统语音。"); speechSynthesis.speak(utterance); }
  async function save(destination: "queue" | "learned") { if (!entry) return; setMessage("正在保存…"); setError(""); const item = { word: entry.word, phonetic: entry.phonetic, wordType: entry.wordType, meaning: entry.meaning, details: `词典查询 · ${entry.cefrLevel}`, sourceWord: "法语词典" }; try { const response = await fetch(destination === "queue" ? "/api/queue" : "/api/words", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(destination === "queue" ? { items: [item] } : item) }); if (!response.ok) throw new Error(); setMessage(destination === "queue" ? "已加入学习清单" : "已标为已学"); onUpdated(); } catch { setMessage(""); setError("保存失败，请重试"); } }
  return <section className="dictionary"><div className="explorer-heading"><div><p className="panel-kicker">发音与释义</p><h3>法语词典</h3></div></div><form onSubmit={lookup}><input value={word} onChange={(event) => setWord(event.target.value)} placeholder="输入法语单词" autoComplete="off"/><button disabled={loading}>{loading ? "查询中…" : "查询"}</button></form>{error && <p className="explorer-error">{error}</p>}{entry && <article><button type="button" className="dictionary-play" onClick={play} aria-label={`播放 ${entry.word}`}>▶</button><div><h4>{entry.word}</h4><span>{entry.phonetic}</span></div><div><b>{entry.wordType}</b><p>{entry.meaning}</p><small>{entry.cefrLevel}</small><div className="dictionary-actions"><button onClick={() => save("queue")}>加入学习清单</button><button onClick={() => save("learned")}>标为已学</button></div>{message && <em>{message}</em>}</div></article>}</section>;
}
