"use client";
import { useEffect,useRef,useState } from "react";
type Rec={continuous:boolean;interimResults:boolean;lang:string;start():void;stop():void;onresult:((e:any)=>void)|null;onend:(()=>void)|null;onerror:(()=>void)|null};
declare global{interface Window{SpeechRecognition?:new()=>Rec;webkitSpeechRecognition?:new()=>Rec}}
const sample="Bonjour, bienvenue en France. Aujourd’hui, nous allons apprendre quelques mots ensemble.";
const wordsOf=(s:string)=>s.match(/[\p{L}\p{M}'’-]+/gu)??[];
export default function Home(){
 const[text,setText]=useState(sample),[words,setWords]=useState(wordsOf(sample)),[index,setIndex]=useState(0),[running,setRunning]=useState(false);
 const[playback,setPlayback]=useState<"once"|"repeat">("repeat"),[advance,setAdvance]=useState<"voice"|"button">("voice"),[status,setStatus]=useState("Ready");
 const mic=useRef<Rec|null>(null),active=useRef(false),pos=useRef(0),list=useRef(words),playMode=useRef(playback),advanceMode=useRef(advance),last=useRef(0);
 useEffect(()=>{active.current=running},[running]);useEffect(()=>{pos.current=index},[index]);useEffect(()=>{list.current=words},[words]);
 function stop(label="Paused"){active.current=false;setRunning(false);speechSynthesis.cancel();mic.current?.stop();mic.current=null;setStatus(label)}
 function speak(word:string){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(word);u.lang="fr-FR";u.rate=.72;u.onend=()=>{if(active.current&&playMode.current==="repeat"&&list.current[pos.current]===word)setTimeout(()=>speak(word),3000)};speechSynthesis.speak(u)}
 function next(){const n=pos.current+1;if(n>=list.current.length){stop("Complete — très bien!");return}pos.current=n;setIndex(n);speak(list.current[n])}
 function listen(){const R=window.SpeechRecognition??window.webkitSpeechRecognition;if(!R){setStatus("Voice unavailable — choose Button");return}const r=new R();r.continuous=true;r.interimResults=true;r.lang="en-US";r.onresult=e=>{let s="";for(let i=0;i<e.results.length;i++)s+=` ${e.results[i][0].transcript}`;const now=Date.now();if(/\b(ok|okay)\b/i.test(s)&&now-last.current>1200){last.current=now;next()}};r.onend=()=>{if(active.current&&advanceMode.current==="voice")try{r.start()}catch{}};r.onerror=()=>setStatus("Microphone blocked — choose Button");mic.current=r;try{r.start()}catch{}}
 function start(){const parsed=wordsOf(text);if(!parsed.length){setStatus("Enter French text first");return}const at=index<parsed.length?index:0;setWords(parsed);list.current=parsed;setIndex(at);pos.current=at;active.current=true;setRunning(true);setStatus(advance==="voice"?'Listening for “OK”':"Press Next word");speak(parsed[at]);if(advance==="voice")listen()}
 function chooseAdvance(value:"voice"|"button"){setAdvance(value);advanceMode.current=value;if(running){mic.current?.stop();mic.current=null;setStatus(value==="voice"?'Listening for “OK”':"Press Next word");if(value==="voice")setTimeout(listen,100)}}
 function reset(){stop("Ready");setIndex(0);pos.current=0}useEffect(()=>()=>{speechSynthesis.cancel();mic.current?.stop()},[]);
 return <main><header><span>É</span><div><h1>Écoute</h1><p>French word practice</p></div></header><section className="card"><label htmlFor="text">French text</label><textarea id="text" value={text} onChange={e=>{stop("Ready");setText(e.target.value);setWords(wordsOf(e.target.value));setIndex(0);pos.current=0}}/><p className="count">{wordsOf(text).length} words</p><div className="options"><fieldset><legend>Move to next word</legend><div><button className={advance==="voice"?"selected":""} onClick={()=>chooseAdvance("voice")}><b>Voice</b><small>Say “OK”</small></button><button className={advance==="button"?"selected":""} onClick={()=>chooseAdvance("button")}><b>Button</b><small>Press Next</small></button></div></fieldset><fieldset><legend>Playback</legend><div><button className={playback==="once"?"selected":""} onClick={()=>{setPlayback("once");playMode.current="once"}}><b>Once</b><small>Play one time</small></button><button className={playback==="repeat"?"selected":""} onClick={()=>{setPlayback("repeat");playMode.current="repeat"}}><b>Repeat</b><small>Every 3 sec</small></button></div></fieldset></div><section className="player"><div className="meta"><span>Word {Math.min(index+1,words.length||1)} / {words.length}</span><span>{status}</span></div><h2>{words[index]??"—"}</h2><div className="bar"><i style={{width:`${words.length?(index+1)/words.length*100:0}%`}}/></div><div className="actions">{running?<button className="start" onClick={()=>stop()}>Pause</button>:<button className="start" onClick={start}>Start</button>}<button className="next" onClick={next}>Next word →</button><button className="reset" onClick={reset}>Reset</button></div></section></section><footer>Uses your browser’s French voice.</footer></main>
}
